export const PATIENT_LOGIN = "PATIENT_LOGIN";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SET_CURRENT_USER_INSURANCE = "SET_CURRENT_USER_INSURANCE";
export const GET_ERRORS = "GET_ERRORS";
